#index:
#    path: /
#    controller: App\Controller\DefaultController::index
videos:
  path: /videos
  controller: App\Controller\VideoController::buscarTodos
  methods:
    - GET
  
video:
  path: /videos/{id}
  controller: App\Controller\VideoController::buscarUm
  methods:
    - GET

remove_video:
  path: /videos/{id}
  controller: App\Controller\VideoController::remove
  methods:
    - DELETE
  
nova_video:
  path: /videos
  controller: App\Controller\VideoController::novo
  methods:
    - POST

atualiza_video:
  path: /videos/{id}
  controller: App\Controller\VideoController::atualiza
  methods:
    - PUT

categorias:
  path: /categorias
  controller: App\Controller\CategoriaController::buscarTodos
  methods:
    - GET
  
categoria:
  path: /categorias/{id}
  controller: App\Controller\CategoriaController::buscarUm
  methods:
    - GET

remove_categoria:
  path: /categorias/{id}
  controller: App\Controller\CategoriaController::remove
  methods:
    - DELETE
  
nova_categoria:
  path: /categorias
  controller: App\Controller\CategoriaController::novo
  methods:
    - POST

atualiza_categoria:
  path: /categorias/{id}
  controller: App\Controller\CategoriaController::atualiza
  methods:
    - PUT

videos_categoria:
  path: /categorias/{id}/videos
  controller: App\Controller\VideoController::buscaPorCategoria
  methods:
    - GET
